MASTER_SYMBOLS = [
    # --- Major Pairs ---
    {"symbol": "EURUSD=X", "name": "EUR/USD", "type": "forex", "exchange": "FX", "category": "major"},
    {"symbol": "GBPUSD=X", "name": "GBP/USD", "type": "forex", "exchange": "FX", "category": "major"},
    {"symbol": "USDJPY=X", "name": "USD/JPY", "type": "forex", "exchange": "FX", "category": "major"},
    {"symbol": "USDCHF=X", "name": "USD/CHF", "type": "forex", "exchange": "FX", "category": "major"},
    {"symbol": "AUDUSD=X", "name": "AUD/USD", "type": "forex", "exchange": "FX", "category": "major"},
    {"symbol": "USDCAD=X", "name": "USD/CAD", "type": "forex", "exchange": "FX", "category": "major"},
    {"symbol": "NZDUSD=X", "name": "NZD/USD", "type": "forex", "exchange": "FX", "category": "major"},

    # --- Minor / Cross Pairs ---
    {"symbol": "EURGBP=X", "name": "EUR/GBP", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "EURJPY=X", "name": "EUR/JPY", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "EURCHF=X", "name": "EUR/CHF", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "EURAUD=X", "name": "EUR/AUD", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "EURCAD=X", "name": "EUR/CAD", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "EURNZD=X", "name": "EUR/NZD", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "GBPJPY=X", "name": "GBP/JPY", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "GBPCHF=X", "name": "GBP/CHF", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "GBPAUD=X", "name": "GBP/AUD", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "GBPCAD=X", "name": "GBP/CAD", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "GBPNZD=X", "name": "GBP/NZD", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "AUDJPY=X", "name": "AUD/JPY", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "AUDCHF=X", "name": "AUD/CHF", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "AUDCAD=X", "name": "AUD/CAD", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "AUDNZD=X", "name": "AUD/NZD", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "CADJPY=X", "name": "CAD/JPY", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "CADCHF=X", "name": "CAD/CHF", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "CHFJPY=X", "name": "CHF/JPY", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "NZDJPY=X", "name": "NZD/JPY", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "NZDCHF=X", "name": "NZD/CHF", "type": "forex", "exchange": "FX", "category": "minor"},
    {"symbol": "NZDCAD=X", "name": "NZD/CAD", "type": "forex", "exchange": "FX", "category": "minor"},

    # --- Exotic Pairs ---
    {"symbol": "USDINR=X",  "name": "USD/INR",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDSGD=X",  "name": "USD/SGD",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDHKD=X",  "name": "USD/HKD",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDMXN=X",  "name": "USD/MXN",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDZAR=X",  "name": "USD/ZAR",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDTRY=X",  "name": "USD/TRY",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDNOK=X",  "name": "USD/NOK",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDSEK=X",  "name": "USD/SEK",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDDKK=X",  "name": "USD/DKK",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDPLN=X",  "name": "USD/PLN",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "USDTHB=X",  "name": "USD/THB",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "EURSGD=X",  "name": "EUR/SGD",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "EURINR=X",  "name": "EUR/INR",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "GBPINR=X",  "name": "GBP/INR",  "type": "forex", "exchange": "FX", "category": "exotic"},
    {"symbol": "JPYINR=X",  "name": "JPY/INR",  "type": "forex", "exchange": "FX", "category": "exotic"},
]
